/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicTacToe_GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author SHU
 */
public class TicTacToe_s extends javax.swing.JFrame {
    int turn = 2;
    int buttonused[]={1,0,0,0,0,0,0,0,0,0};
    int wonned=0;
    
    int p1won[]={1,0,0,0,0,0,0,0,0,0};
    int p2won[]={1,0,0,0,0,0,0,0,0,0};
    
    int checkp1()
    {
        
        if(p1won[1]==1 && p1won[2]==1 && p1won[3]==1)
        {
            wonned=1;
            return 1;
            
            
        }
        
        if(p1won[4]==1 && p1won[5]==1 && p1won[6]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p1won[7]==1 && p1won[8]==1 && p1won[9]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p1won[1]==1 && p1won[4]==1 && p1won[7]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p1won[2]==1 && p1won[5]==1 && p1won[8]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p1won[3]==1 && p1won[6]==1 && p1won[9]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p1won[1]==1 && p1won[5]==1 && p1won[9]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p1won[7]==1 && p1won[5]==1 && p1won[3]==1)
        {
            wonned=1;
            return 1;
        }
        //checktie();
        return 0; 
    }
    
    
    int checkp2()
    {
            
        if(p2won[1]==1 && p2won[2]==1 && p2won[3]==1)
        {
            wonned=1;
            return 1;
        }
        
        if(p2won[4]==1 && p2won[5]==1 && p2won[6]==1)
        {
            
            wonned=1;
            return 1;
        }
         
        if(p2won[7]==1 && p2won[8]==1 && p2won[9]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p2won[1]==1 && p2won[4]==1 && p2won[7]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p2won[2]==1 && p2won[5]==1 && p2won[8]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p2won[3]==1 && p2won[6]==1 && p2won[9]==1)
        {
            wonned=1;
            return 1;
        }
         
        if(p2won[1]==1 && p2won[5]==1 && p2won[9]==1)
        {
            wonned=1;
            return 1;
            
        }
         
        if(p2won[7]==1 && p2won[5]==1 && p2won[3]==1)
        {
            wonned=1;
            return 1;
        }
        
        checktie();
        return 0;
    }
    
    void checktie()
    {
       if (turn>10 && wonned==0)
       {
            JOptionPane.showMessageDialog(rootPane,"!!! This is Tie  !!!");
       }
    
    }
    
    /**
     * Creates new form TicTacToe_s
     */
    public TicTacToe_s() {
        initComponents();
        setSize(1200,600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        roundx = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        roundo = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Player X:");
        jPanel6.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        roundx.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        roundx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/arrow.png"))); // NOI18N
        jPanel7.add(roundx, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("Player O:");
        jPanel11.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        roundo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        roundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/arrowempty.png"))); // NOI18N
        jPanel12.add(roundo, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/empty.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jbtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/exit.png"))); // NOI18N
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel16.add(jbtnReset, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jbtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe_GUI/exitbtn.png"))); // NOI18N
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel17.add(jbtnExit, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel17);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnResetActionPerformed
       
    void reset()
    {
            int i;
               roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("empty.png")));
        
        turn = 2;
        for(i=0;i<11;i++)
        {
            buttonused[i]=0;
            p1won[i]=0;
            p2won[i]=0; 
         }
                    
      
    }
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(buttonused[1]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            buttonused[1]=1;
            p1won[1]=1;
            
            
    
            }
            else
            {
            turn++;
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[1]=1;
            p2won[1]=1;
            
                      
                      roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
       
            
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
       
        
        
            int result1= checkp1();
            int result2= checkp2();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
            }
            else if (result2==1)
            {
                JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
            }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(buttonused[2]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            buttonused[2]=1;
            p1won[2]=1;
                      
                   roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
       
            }
            else
            {
            turn++;
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[2]=1;
            p2won[2]=1;
            
                                      roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));      
      
       
            
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
                // TODO add your handling code here:
        
        
            int result1= checkp1();
            int result2= checkp2();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
            }
            else if (result2==1)
            {
                JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
            }
        
        
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(buttonused[3]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            buttonused[3]=1;
            p1won[3]=1;
                      
                    roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            
            }
            else
            {
            turn++;
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[3]=1;
            p2won[3]=1;
                               roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
                // TODO add your handling code here:
        
        
            int result1= checkp1();
            int result2= checkp2();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
            }
            else if (result2==1)
            {
                JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
            }
        
        
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(buttonused[4]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            buttonused[4]=1;
            p1won[4]=1;
            
                    roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            
            }
            else
            {
            turn++;
            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[4]=1;
            p2won[4]=1;
                                  roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
           
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
        
        
            int result1= checkp1();
            int result2= checkp2();
            
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
            }
            else if (result2==1)
            {
                JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
            }
        
        
              
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(buttonused[5]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            buttonused[5]=1;
            p1won[5]=1;
            
                       roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            
            }
            else
            {
            turn++;
            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[5]=1;
            p2won[5]=1;
            
 
                                  roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
                // TODO add your handling code here:           

                        int result1= checkp1();
                        int result2= checkp2();

                        if(result1==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
                        }
                        else if (result2==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
                        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if(buttonused[6]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            buttonused[6]=1;
            p1won[6]=1;
            
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            
            }
            else
            {
            turn++;
            jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[6]=1;
            p2won[6]=1;
            
                                      roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));      

            
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
                
                        int result1= checkp1();
                        int result2= checkp2();

                        if(result1==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
                        }
                        else if (result2==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
                        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(buttonused[7]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            buttonused[7]=1;
            p1won[7]=1;
            
                         roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            }
            else
            {
            turn++;
            jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[7]=1;
            p2won[7]=1;
            
            
                                  roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
                // TODO add your handling code here:

                        int result1= checkp1();
                        int result2= checkp2();

                        if(result1==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
                        }
                        else if (result2==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
                        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
if(buttonused[8]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            buttonused[8]=1;
            p1won[8]=1;
                        roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
        
            
            }
            else
            {
            turn++;
            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[8]=1;
            p2won[8]=1;
            
                               roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            
            
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
                // TODO add your handling code here:

                        int result1= checkp1();
                        int result2= checkp2();

                        if(result1==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
                        }
                        else if (result2==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
                        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
if(buttonused[9]==0)
        {
            if(turn%2==0)
            {
            turn++;
            jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
            buttonused[9]=1;
            p1won[9]=1;
            
            
                    roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            
            
            }
            else
            {
            turn++;
            jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("circle.png")));
            buttonused[9]=1;
            p2won[9]=1;
            
            
                              roundx.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrow.png")));
            roundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("arrowempty.png")));
            
            
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"!!! This Button Used Already");
        }
                // TODO add your handling code here:
                        int result1= checkp1();
                        int result2= checkp2();

                        if(result1==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 1 (X) has won **");
                        }
                        else if (result2==1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "** Player 2 (O) has won **");
                        }

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe_s().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JLabel roundo;
    private javax.swing.JLabel roundx;
    // End of variables declaration//GEN-END:variables
}
